### ISSUE TITLE
v10 warning on hot reload of custom node/edge types

### ISSUE THREAD

**Issue by AndrewRayCode** [wbkd/react-flow#2006]
### Describe the Bug

There is a large warning in the console from react-flow on hot reload if using custom node or edge types, even if they don't change.

### Steps to Reproduce the Bug or Issue

Set up a hot reloading environment.

Pass in a custom
```
                  nodeTypes={nodeTypes}
                  edgeTypes={edgeTypes}
```

Trigger a hot reload, without changing the node or edge custom type files.

This warning appears in the console on every reload, which takes up a lot of room:

```
react_devtools_backend.js:3973 React Flow: It looks like that you created a new nodeTypes or edgeTypes object. If this wasn't on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them. 
    at eval (webpack-internal:///./node_modules/react-flow-renderer/dist/esm/index.js:3502:20)
    at div
    at TabPanel (webpack-internal:///./src/Tabs.tsx:116:24)
    at TabPanels (webpack-internal:///./src/Tabs.tsx:104:24)
    at Tabs (webpack-internal:///./src/Tabs.tsx:34:23)
    at div
    at div
    at eval (webpack-internal:///./node_modules/react-multi-split-pane/dist/lib/Pane.js:13:30)
    at div
    at eval (webpack-internal:///./node_modules/react-multi-split-pane/dist/lib/SplitPane.js:128:58)
    at div
    at Editor (webpack-internal:///./src/Editor.tsx:383:66)
    at LoadableComponent (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:122:37)
    at Editor
    at MyApp (webpack-internal:///./pages/_app.tsx:25:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:254:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:750:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:889:25)
overrideMethod @ react_devtools_backend.js:3973
eval @ index.js?ab76:3372
updateMemo @ react-dom.development.js?61bb:15867
useMemo @ react-dom.development.js?61bb:16413
useMemo @ react.development.js?72d0:1532
useNodeOrEdgeTypes @ index.js?ab76:3367
eval @ index.js?ab76:3556
renderWithHooks @ react-dom.development.js?61bb:14985
updateForwardRef @ react-dom.development.js?61bb:17044
beginWork @ react-dom.development.js?61bb:19098
beginWork$1 @ react-dom.development.js?61bb:23940
performUnitOfWork @ react-dom.development.js?61bb:22776
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
flushSync @ react-dom.development.js?61bb:22467
scheduleRefresh @ react-dom.development.js?61bb:24429
renderer.scheduleRefresh @ react_devtools_backend.js:6402
eval @ react-refresh-runtime.development.js?1816:304
performReactRefresh @ react-refresh-runtime.development.js?1816:293
eval @ helpers.js?e64a:124
setTimeout (async)
scheduleUpdate @ helpers.js?e64a:119
eval @ Editor.tsx?8971:1047
./src/Editor.tsx @ src_Editor_tsx.e2fe3000e6b56126dc9e.hot-update.js:18
options.factory @ webpack.js?ts=1648052829121:685
__webpack_require__ @ webpack.js?ts=1648052829121:37
_requireSelf @ webpack.js?ts=1648052829121:394
apply @ webpack.js?ts=1648052829121:1151
(anonymous) @ webpack.js?ts=1648052829121:622
internalApply @ webpack.js?ts=1648052829121:620
(anonymous) @ webpack.js?ts=1648052829121:561
waitForBlockingPromises @ webpack.js?ts=1648052829121:514
(anonymous) @ webpack.js?ts=1648052829121:559
Promise.then (async)
(anonymous) @ webpack.js?ts=1648052829121:558
Promise.then (async)
(anonymous) @ webpack.js?ts=1648052829121:537
Promise.then (async)
hotCheck @ webpack.js?ts=1648052829121:528
tryApplyUpdates @ hot-dev-client.js?5345:252
handleSuccess @ hot-dev-client.js?5345:66
processMessage @ hot-dev-client.js?5345:176
eval @ hot-dev-client.js?5345:32
eval @ eventsource.js?a343:38
handleMessage @ eventsource.js?a343:36
react_devtools_backend.js:3973 React Flow: It looks like that you created a new nodeTypes or edgeTypes object. If this wasn't on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them. 
    at eval (webpack-internal:///./node_modules/react-flow-renderer/dist/esm/index.js:3502:20)
    at div
    at TabPanel (webpack-internal:///./src/Tabs.tsx:116:24)
    at TabPanels (webpack-internal:///./src/Tabs.tsx:104:24)
    at Tabs (webpack-internal:///./src/Tabs.tsx:34:23)
    at div
    at div
    at eval (webpack-internal:///./node_modules/react-multi-split-pane/dist/lib/Pane.js:13:30)
    at div
    at eval (webpack-internal:///./node_modules/react-multi-split-pane/dist/lib/SplitPane.js:128:58)
    at div
    at Editor (webpack-internal:///./src/Editor.tsx:383:66)
    at LoadableComponent (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:122:37)
    at Editor
    at MyApp (webpack-internal:///./pages/_app.tsx:25:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:254:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:750:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:889:25)
```

### Expected behavior

No warning to be issued, as was the pre v10 behavior

### Platform

- OS: Mac
- Browser: Chrome
- Version: 10.0.3

### Additional context

I import my custom node and edge type from a separate file. Above my component, in the file that hot reloads, I have

```
const nodeTypes = {
  special: FlowNodeComponent,
};

const edgeTypes = {
  special: FlowEdgeComponent,
};
```

Maybe it's these consts getting re-created that triggers the issue? The components themselves likely don't change at all with hot reload.

**Comment by moklick** [comment]
If this happens while developing on hot reload you can ignore the warning. If this happens every time your component gets re-rendered, you should create your custom nodes outside of the component or use `useMemo`: https://reactflow.dev/docs/guides/troubleshooting/#it-looks-like-you-have-created-a-new-nodetypes-or-edgetypes-object-if-this-wasnt-on-purpose-please-define-the-nodetypesedgetypes-outside-of-the-component-or-memoize-them

**Comment by AndrewRayCode** [comment]
@moklick the const code above is created outside the component. On Next.js fast refresh I think some modules get re-executed if they or their dependencies have changed.

I haven't seen this warning in a while so I'm not sure if something changed in the latest version. I just wanted to call out that the definitions are outside the component (and in the same component file, which I think next.js fully reloads)
