### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by mac24079** [wbkd/react-flow#2021]
### Describe the Bug

- At present, when you clone the react-flow repository and follow the same instructions to run the app on localhost, your local browser console shows an error -  Uncaught ReferenceError: require is not defined.

-  Also, the react-flow app works fine without errors in my Mac operating system but in windows it is throwing the above stated error.

### Your Example Website or App

https://github.com/wbkd/react-flow

### Steps to Reproduce the Bug or Issue

1. Cloned repo locally (https://github.com/wbkd/react-flow ) to C:\usr\react-flow
2.  Inside react-flow run the following commands:
4.  cd example && npm install
5.  Then with windows cmd in C:\development\react-flow:
6.  npm start
7.  Then with separate windows cmd in C:\development\theraflow-designer\react-flow:
8.  cd example && npm start

When accessing with any browser localhost:3000 generates only empty page with following errors in console:

### Expected behavior

As a user I expected the app to run smoothly on Windows operating system like this:

![image](https://user-images.githubusercontent.com/23357897/160098734-bc6510f1-5ae3-4f23-b8c0-1927b542c806.png)

But seeing the following error in console:

extends.js:17 Uncaught ReferenceError: require is not defined
    at Module.../dist/esm/index-5236d2af.js (extends.js:17:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module.../dist/esm/index.js (slicedToArray.js:7:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/Basic/index.tsx (bundle.js:15:77)
    at Module.options.factory (react refresh:6:1)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/23357897/160092110-d46aacdd-eef6-4e02-ae89-7d73eb32799a.png)

### Platform

- OS: [Windows 10]
- Browser: [Chrome]
- Node version: v17.8.0
- Npm version: v8.1.2

### Additional context

The app runs fine with Mac but having issues running with Windows.

**Comment by pr0grara** [comment]
I am having a similar issue but not using React Flow. Some of my possibly relevant dependencies:
    "react": "^18.2.0",
    "styled-components": "^5.3.6",
    "webpack": "^5.74.0"

the error i'm getting (quite similar):

Uncaught ReferenceError: require is not defined
    at Object.events (external node-commonjs "events":1:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/webpack/hot/emitter.js (emitter.js:1:20)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/webpack/hot/dev-server.js (dev-server.js:63:19)
    at __webpack_require__ (bootstrap:24:1)
    at startup:4:1
    at startup:5:1

![Screenshot 2023-01-21 at 10 57 46 PM](https://user-images.githubusercontent.com/62962385/213904479-631d3060-0f05-4af8-844a-96454d8f9ba0.png)

MacOS
Chrome
Node -v: 15.7.0
Npm -v: 7.6.1

**Comment by moklick** [comment]
please re-open if the issue persists. It should be fixed by now.
