### ISSUE TITLE
@testing-library/react Error: Uncaught [TypeError: Cannot redefine property: onresize]

### ISSUE THREAD

**Issue by tbertrand7** [wbkd/react-flow#2108]
### Describe the Bug

When running unit tests using jest & @testing-library/react, I get the following error when trying to render a component containing a ReactFlow instance:

Error: Uncaught [TypeError: Cannot redefine property: onresize]

### Steps to Reproduce the Bug or Issue

```jsx
import { render } from '@testing-library/react';

test('example', () => {
  window.ResizeObserver = jest.fn(() => ({
      observe: jest.fn(),
      unobserve: jest.fn(),
      disconnect: jest.fn(),
  }));

  render(
    <div style={{ height: 1200, width: 800 }}>
      <ComponentContainingReactFlow />
    </div>,
  );
});
```

### Expected behavior

The test should not throw an error.

### Platform

- OS: macOS
- Browser: jsdom
- Version: 10.1.2

**Comment by platonlukyanov** [comment]
Have the same problem

**Comment by retronouns** [comment]
You can fix this by replacing the `window.onresize = () => { console.log('do stuff'); }` assignment with `window.addEventListener('resize', () => { console.log('do stuff'); })`

**Comment by AustinGilliam** [comment]
I'm also having this issue in a fresh application with version 10.3.11. @moklick I see the use of `window.onresize` in the `useResizeHandler` hook, but the log below seems to point to zustand. However, I don't see an open issue in zustand or @testing-library/react related to this. Do you have any insight?

 TypeError: Cannot redefine property: onresize

      12 |
      13 |   test('Should display logo', () => {
    > 14 |     render(<App />);
         |     ^
      15 |     screen.getByText('App');
      16 |   });
      17 | });

      at useStore (node_modules/react-flow-renderer/node_modules/zustand/esm/index.js:108:10)
      at invokePassiveEffectCreate (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:23574:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:23447:14)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22269:3)
      at node_modules/react-dom/cjs/react-dom.development.js:11327:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11322:9)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11309:3)
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22387:7)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at Object.<anonymous> (src/App.test.tsx:14:5)

**Comment by moklick** [comment]
This will be fixed in v11!
